services:
  intranet:
    build:
      context: ./
      dockerfile: intranet/Dockerfile
    image: intranet
    container_name: intranet
    networks:
      - asa-network
  portal:
    build:
      context: ./
      dockerfile: portal/Dockerfile
    image: portal
    container_name: portal
    networks:
      - asa-network
  webmail:
      build:
        context: ./webmail
      image: webmail
      container_name: webmail
      restart: always
      tty: true
      volumes:
        - ./webmail1/rainloop:/var/www/html/rainloop
      depends_on:
        - email
      networks:
        - asa-network
  proxy:
    build:
      context: ./
      dockerfile: proxy/Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - intranet
      - portal
    networks:
      - asa-network
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: dns
    container_name: dns
    hostname: ns1.asa.br
    restart: always
    tty: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-network
  email:
    build: ./email
    image: email
    container_name: email
    ports:
      - "25:25/tcp"
      - "100:100/tcp"
      - "143:143/tcp"
      - "587:587/tcp"
      - "993:993/tcp"
      - "995:995/tcp"
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge
